import numpy as np
from data import * # Data.py

print("Matriks a =",a)
print()
print("Matriks b =",b)
print()
print("Matriks c =",c)
print()
print("Matriks d =",d)
print()
print("Matriks e")
print(e)
print("Matriks f")
print(f)
print("Matriks g =",g)
print()
print("Matriks h =",h)
print()
print("Matriks i =",i)
print()
print("Matriks j =")
print(j)
print("Matriks k =")
print(k)
print("Matriks l =")
print(l)
print("Matriks m =")
print(m)
print("Matriks n =")
print(n)